import type { Metadata } from "next";
import { connectToMongoDB } from "@/db/db";
import localFont from "next/font/local";
import { SongBar } from "@/components/SongBar";
import NavBar from "@/components/NavBar";
import "./globals.css";
import { auth } from "@/auth";
import ModalAddSongToPlaylist from "@/components/modals/ModalAddSongToPlaylist";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  connectToMongoDB();
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ring-0 outline-none relative max-w-[100vw] overflow-x-hidden h-[100dvh] grid grid-rows-[70px_auto_80px] m-0 p-0`}
      >
        <NavBar />
        <div className="overflow-y-scroll w-full ">{children}</div>
        <SongBar session={session} />
        <ModalAddSongToPlaylist />
      </body>
    </html>
  );
}
