import type { Metadata } from "next";
import localFont from "next/font/local";
import { SongBar } from "@/components/SongBar";
import NavBar from "@/components/NavBar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ring-0 outline-none relative max-w-screen overflow-x-hidden h-[100dvh] grid grid-rows-[70px_auto_80px]`}
      >
        <NavBar />
        <div className="overflow-y-scroll ">{children}</div>
        <SongBar />
      </body>
    </html>
  );
}
